name: Build nina

on:
  workflow_dispatch:
    inputs:
      build_target:
        type: choice
        description: 'Source to build'
        required: true
        default: develop
        options: 
        - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    # ------------------------------------------------------------
    # Checkout *your* build project
    # ------------------------------------------------------------
    - name: Checkout build harness
      uses: actions/checkout@v4

    # ------------------------------------------------------------
    # Fetch OnStepX sources into temp directory
    # ------------------------------------------------------------
    - name: Fetch OnStepX sources
      run: |
        case "${{ github.event.inputs.build_target }}" in
          develop)         REF=develop ;;
        esac

        echo "Using NINA ref: $REF"

        git clone --depth 1 --branch "$REF" \
          https://github.com/isbeorn/nina.git nina-src
   
    - name: cd to nina src
      run:
        cd nina-src
        git checkout develop
        git submoudule update --init
    
    - name: Set up .NET 10.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: build nina
      run:
        dotnet build NINA\NINA.csproj
        
      
